import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartCountProvider } from "@/context/CartCountContext";
import ChatWidget from "@/components/ChatWidget";
import { NotificationProvider } from "@/context/NotificationContext";
import { DarkModeProvider } from "@/context/DarkModeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TechHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <DarkModeProvider>
          <NotificationProvider>
            <CartCountProvider>
              {children}
              <ChatWidget />
            </CartCountProvider>
          </NotificationProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
